/**:
    ros__parameters:
      registration_method: "NDT_OMP"
      score_threshold: 10.0
      ndt_resolution: 2.0
      ndt_step_size: 0.1
      ndt_num_threads: 0
      transform_epsilon: 0.01
      voxel_leaf_size: 0.4
      scan_max_range: 30.0
      scan_min_range: 1.0
      scan_period: 0.1
      use_pcd_map: true
      
      # map_path: "/home/acca/catkin_ws/src/lidar_localization_ros2-humble/resource/2023_kcity.pcd"
      # map_path: "/home/acca/catkin_ws/src/lidar_localization_ros2-humble/resource/GlobalMap.pcd"
      map_path: "/home/acca/ACCA2024/2023_kcity.pcd"

      set_initial_pose: false

      # initial_pose_x: 42.999847412109375
      # initial_pose_y: -74.63196563720703
      # initial_pose_z: 0.0
      # initial_pose_qx: 0.0
      # initial_pose_qy: 0.0
      # initial_pose_qz: 0.10377107833105886
      # initial_pose_qw: 0.9946012081744167

      initial_pose_x: -30.727670669555664
      initial_pose_y: -66.93682861328125
      initial_pose_z: 0.0
      initial_pose_qx: 0.0
      initial_pose_qy: 0.0
      initial_pose_qz: -0.05938490406231933
      initial_pose_qw: 0.998235159253324
      
      use_odom: false
      use_imu: false
      enable_debug: true
      global_frame_id: map
      odom_frame_id: odom
      base_frame_id: base_link
      is_publish_tf: false
