/**:
    ros__parameters:
      registration_method: "NDT_OMP"
      score_threshold: 100.0
      ndt_resolution: 2.0
      ndt_step_size: 0.1
      ndt_num_threads: 0
      transform_epsilon: 0.0
      voxel_leaf_size: 0.5
      scan_max_range: 100.0
      scan_min_range: 1.0
      scan_period: 0.1
      use_pcd_map: true
      map_path: "/home/acca/catkin_ws/src/lidar_localization_ros2-humble/resource/GlobalMap.pcd"
      set_initial_pose: true
      initial_pose_x: -31.77552032470703
      initial_pose_y: -64.61795043945312
      initial_pose_z: 0.0
      initial_pose_qx: 0.0
      initial_pose_qy: 0.0
      initial_pose_qz: -0.055078838853748896
      initial_pose_qw: 0.9984820086063257
      use_odom: false
      use_imu: false
      enable_debug: true
      global_frame_id: map
      odom_frame_id: odom
      base_frame_id: base_link
