map_odom_tf_node:
  ros__parameters:
      # odometry topic
      odom: "/odometry/kalman"  

      # pcl topic
      pcl_pose: "/pcl_pose"   

      # pcl_score topic
      pcl_score: "/pcl_score"   

      # queue size to check tf validation. integer
      queue_length: 15 # Tune     

      # distance threshold between predicted pose and subscribed pose. double
      pose_threshold: 0.2     

      # pcl_score threshold. double
      score_threshold: 0.3     

      # waiting time for reinitialize. double
      reinitialize_waiting: 3.0 

      # threshold for queue to determine tf is valid. int. 
      # this field must be lesser than queue_length (or same)
      valid_threshold: 5 # Tune  

      # threshold for queue to determine tf is invalid. int.
      # this field must be lesser than queue_length (or same)
      invalid_threshold: 15 # Tune  

      # tf distance threshold to prevent jumped tf.
      tf_distance_threshold: 20.0

      # count threshold. If tf distances have bigger value than tf_distance_threshold for reinitialize_count_threshold times, it will be ignored.
      reinitialize_count_threshold: 5